### ISSUE TITLE
eyelinker: Import ASC Files from EyeLink Eye Trackers

### ISSUE THREAD

**Issue by rociojoo** [cran-task-views/Tracking#11]
### Are you the author of the package?

No

### Is the package on a specific repository?

CRAN

### Please provide the URL of the package repository

https://cran.r-project.org/package=eyelinker

### Is there a dedicated website for the documentation (e.g. a pkgdown website)?

Not really but see https://cran.r-project.org/web/packages/eyelinker/vignettes/basics.html

### If you are the author of the package, does it pass CRAN check tests?

Yes (CRAN package).

### Additional information

**Briefly, can you describe the purpose of this package and how it fits into the Tracking CTV?**
It works with eye tracking data (x, y, time)

**In terms of the tracking workflow (see Figure in the CTV), where does the package fit?** (Feel free to mention any particular functions and how they fit as well.) 
I'd say postprocessing because it allows going from raw ASC files to tidy data frames. 
`downsampling` is done with the `filter` function in `dplyr` so I wouldn't count it as a role of the package
It seems to be more like a tutorial to deal with eye tracking data that includes examples. 

@basille I would appreciate your opinion on this one.

**Comment by basille** [comment]
From what I understand, it really is a single function ([`read.asc`](https://github.com/a-hurst/eyelinker/blob/master/R/eyelink_parser.R)) to import plain-text ASC data files from EyeLink eye trackers. Behind the scene, there is quite a lot of heavy processing to get usable data in R though.

To me, it's clearly pre-processing (not post-), as it goes from raw data to x/y/t format. But we should make it explicit in the CTV that import is in this category.

**Comment by rociojoo** [comment]
added to `Tracking_tbl.csv`
