### ISSUE TITLE
saccades: Saccade and Fixation Detection in R

### ISSUE THREAD

**Issue by rociojoo** [cran-task-views/Tracking#15]
### Are you the author of the package?

No

### Is the package on a specific repository?

GitHub

### Please provide the URL of the package repository

https://github.com/tmalsburg/saccades

### Is there a dedicated website for the documentation (e.g. a pkgdown website)?

No

### If you are the author of the package, does it pass CRAN check tests?

I don't know

### Additional information

**Briefly, can you describe the purpose of this package and how it fits into the Tracking CTV?**
It detects saccades, fixations, and blinks in eyetracking data. 
However, on CRAN: `Archived on 2022-04-10 at the request of the maintainer. ` https://cran.r-project.org/web/packages/saccades/index.html
So I'm just opening the issue to have a record of this package

**In terms of the tracking workflow (see Figure in the CTV), where does the package fit?** (Feel free to mention any particular functions and how they fit as well.) 
It would've fallen under behavioral pattern identification.

**Comment by basille** [comment]
Before we close this issue, shouldn't it be added to the list though? So we have it just in case development starts again (with the same or new maintainer)… That would seem fair since it is not `declined` because of the focus of the package.

**Comment by rociojoo** [comment]
I think you're right.

**Comment by rociojoo** [comment]
Not adding anything myself yet. I'm focused on finishing the list of packages to create issues for.

**Comment by rociojoo** [comment]
added to `Tracking_tbl.csv`

**Comment by basille** [comment]
Package archived on CRAN on 2022-04-10, and removed from the Tracking CTV.
