### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by rociojoo** [cran-task-views/Tracking#3]
I added the .yaml files for issues but they will only become active once the repo is public. 

Step 2 will be to add links to those issues in the read me. 

Step 3 to make issues about the packages that need to be checked.

**Comment by zeileis** [comment]
Done now 🎉

**Comment by basille** [comment]
Great news @zeileis! Now that the repository is public, can you tell when the actual CTV page on CRAN will be updated? Thanks in advance!

**Comment by zeileis** [comment]
We have contacted all task view maintainers now, telling them that we want to switch in two weeks. I hope that this works out.
