### ISSUE TITLE
alt-text for figure

### ISSUE THREAD

**Issue by rociojoo** [cran-task-views/Tracking#32]
Mathieu @basille , did you modify the line of the workflow figure? And would you like taking a stab at adding alt-text?

**Comment by basille** [comment]
I did not modify it (at least not on purpose). Altogether, it would be good to have a proper implementation to include images in the CTVs, but that's beyond this issue (I just opened [an issue](https://github.com/cran-task-views/ctv/issues/29) in the main CTV repo).

We can use this thread to give a stab at the alt text to add. I don't necessarily have time right away to do it, but I'll add it to my todo list.

**Comment by basille** [comment]
I just gave it a try (and committed as 90abb9eed2d2b8a5d34de2731fe7b68fe9104821):

> Diagram depicting the workflow for data processing and analysis in movement ecology. Three steps are identified: 1) Pre-processing, taking raw data as input and leading to tracking data as output (x, y, t); 2) Post-processing, manipulating tracking data as both input and output; 3) Analysis, which takes tracking data as input for visualization, track description, path reconstruction, behavioral pattern identification, space use, trajectory simulation, and others.

@rociojoo, please review this text. Feel free to modify, and close the issue when you're done.

**Comment by rociojoo** [comment]
Thanks @basille . I'll modify it in the `dev` branch with this proposal:

> Diagram with boxes and arrows depicting the workflow for data processing and analysis in movement ecology. Three steps—represented by arrows in the diagram—are identified: 1) Pre-processing, taking raw data (box on the left) as input and leading to tracking data as output (x, y, t) (box on the center); 2) Post-processing, manipulating tracking data as both input and output; 3) Analysis, which takes tracking data as input for visualization, track description, path reconstruction, behavioral pattern identification, space use, trajectory simulation, and others (all of these represented by boxes on the right).

**Comment by basille** [comment]
Perfect, thanks!
