### ISSUE TITLE
migflow: Calculates the maximum flow through a network

### ISSUE THREAD

**Issue by rociojoo** [cran-task-views/Tracking#38]
### Are you the author of the package?

No

### Is the package on a specific repository?

GitHub

### Please provide the URL of the package repository

https://github.com/KiranLDA/migflow

### If you are the author of the package, does it pass CRAN check tests?

I don't know

### Additional information

**Briefly, can you describe the purpose of this package and how it fits into the Tracking CTV?**
The packages provides a set of functions to set up a migratory connectivity matrix, and then use this matrix to calculate the maximum flow of birds/animal through the migratory network, and then prioritise sites for conservation.

**In terms of the tracking workflow (see Figure in the CTV), where does the package fit?** (Feel free to mention any particular functions and how they fit as well.) 
This is another pkg that I think could fall under `movement but not tracking` (IF it passes the check tests).
Its tracks are actually a series of distances traveled. And there are long and lat of sites, not the individuals. 
So it could go in that section as `migratory connectivity matrix` for conservation purposes.

**Comment by rociojoo** [comment]
added to `Tracking_tbl.csv`

**Comment by basille** [comment]
Does not pass CRAN checks any more, removed from the CTV.
