### ISSUE TITLE
feedr package not on CRAN

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/Tracking#4]
The task view mentions the `feedr` package with `pkg()` markup but the package is not on CRAN. I guess you want to refer to the package on GitHub. Please change the text and markup accordingly, thanks!

**Comment by basille** [comment]
Thanks for the catch! It is indeed a GitHub package… but that should not even be in the CTV in the first place, as it does not pass CRAN checks. I noticed a couple of other inconsistencies in `Tracking.md`, we'll fix that in the coming days.

**Comment by zeileis** [comment]
Sounds good, thanks for your work!

**Comment by zeileis** [comment]
I've removed the `feedr` package now to make `ctv::check_ctv_packages()` happy. I'm keeping this issue open, though, as you mentioned further inconsistencies you want to address.

**Comment by basille** [comment]
Thanks @zeileis. I think we can close this issue now.
