### ISSUE TITLE
Process for packages that have been archived on CRAN

### ISSUE THREAD

**Issue by basille** [cran-task-views/Tracking#49]
After a discussion initiated by @zeileis (#47), let's work on a process for packages that have been archived on CRAN. The aims are twofold: 1) remind the developers that their package is somehow broken, and will thus be removed also from the Tracking CTV if there is no fix; 2) document the situation here.

My suggestion is the following:

1. When a package gets archived on CRAN, it is flagged as "Archived" in the CTVs, and does not get installed automatically with the task view anymore.
2. When the package has been archived on CRAN for 60 days, this automatically opens an issue here with a message indicating which package is problematic. 
3. We (Tracking CTV maintainers) use the package maintainer's email address to contact them, with a simple message explaining the situation (see below), and a link to the issue here. If we get a bounce-back email (ie email not working anymore), we run a quick web search to find another email address for the maintainer.
4. If there is a public repository (e.g. GitHub), we also open an issue there with the same message.
5. If nothing happens after 4 weeks, we remove the package and document the removal using the dedicated [issue template](https://github.com/cran-task-views/Tracking/issues/new?assignees=&labels=removed&template=package-removed.yml&title=Name+of+the+package%3A+description+of+the+package+%28change+this+title%29), and add in the additional information the date at which the maintainer was contacted, the open issue on the package repo (if it exists) and the link to the initial thread from 1. here.

Template for the message:

> **Subject: Package <`abcd`> archived on CRAN and will be removed from the Tracking CTV**
> 
> Dear <`name`>,
> 
> The package <`abcd`> has been archived on CRAN for 60 days, and you are listed as the maintainer. This message is to let you know that your package is currently listed in the Tracking CRAN Task View (https://cran.r-project.org/view=Tracking), but is flagged as "Archived", which means it will not get installed automatically with the CTV.
> 
> If the problem on your package persists for another 4 weeks, and the package is not reinstated on CRAN, it will also be removed from the Tracking CTV. Details of the situation can be found here: https://github.com/cran-task-views/Tracking/issues/<`XX`>
> 
> <`If possible: add details about the issue from CRAN, and how to fix it if it seems easy enough.`>
> 
> Of course, if you are able to fix the problems of the package after it has been removed from the Tracking CTV, you can always ask for reinstatement in the Tracking CTV. In the meanwhile, please feel free to respond to this message or, better, to comment on the issue above.
> 
> Best,
> For the Tracking CTV maintainers,
> <`name of CTV maintainer`>

What do you think @rociojoo?

**Comment by zeileis** [comment]
Thanks, this corresponds to what the automatically generated issue suggests. Two additional comments:

* The issue is not created upon archival on CRAN but only if the package was archived for more than 60 days already on CRAN. Up to that point the package is simply flagged as "Archived" in the task view and not included in the automatic installation of packages from the task view.
* Using the maintainer e-mail address may not work, it is the reason for the CRAN archival in a certain share of the cases. If I notice this, I typically try to have a look at how easy it is to find a current address and then write to that. I find it hard to give an "objective" workflow for this, though.

**Comment by basille** [comment]
This is indeed consistent. Thanks for the precision, that actually allows for 3 months altogether, which is fair. As for the email address, I've been there myself, and it's sometimes a pain to track someone down. Let me reflect on this in the initial post.

**Comment by basille** [comment]
I've updated the initial post, and added a template message. Your turn @rociojoo!

**Comment by zeileis** [comment]
One general remark about the e-mail template: This is "another" essentially auto-generated e-mail the maintainer will receive which may just add to their frustration/stress/reluctance. If I write to package maintainer, I write to them with their name and I sign with my name. Also I include some information that makes it clear that I actually took a look at the package and the issue that caused the archival. As pointed out previously in another discussion: You may perceive this as "arbitrary" but I feel that this is the whole point in my opinion...

**Comment by basille** [comment]
These are good points @zeileis. Yet I wonder how far we should go in accompanying them, especially if they haven't been active on their package for very long. I hear your argument though.

**Comment by zeileis** [comment]
That's something you can decide as a researcher and community member, not necessarily as the task view maintainer. As the task view co-maintainer you have no obligations here. If as a researcher and community member, you feel it's worth your time to help, go for it. If not, not.

**Comment by basille** [comment]
I just sent individualized emails to maintainers/authors of all 4 archived packages. Let's see how this goes.

**Comment by rociojoo** [comment]
Hey @basille and @zeileis thanks for this fruitful conversation. I had a tough time catching up with emails and everything while having a tropical storm and hurricane saying hi. I would not recommend visiting in September. 
I agree with the process above. 
I saw the emails, @basille , thank you for that. I'm guessing there has been no response so far?

**Comment by basille** [comment]
Nothing yet indeed. Let me suggest that we use the axe starting next week.

**Comment by basille** [comment]
Moved to [WORKFLOW.md](https://github.com/cran-task-views/Tracking/blob/main/WORKFLOW.md) for smoother tracking.
