### ISSUE TITLE
animalTrack: Animal track reconstruction for high frequency 2-dimensional (2D) or 3-dimensional (3D) movement data

### ISSUE THREAD

**Issue by basille** [cran-task-views/Tracking#56]
### Why was the package removed?

No longer on CRAN

### URL of the CRAN check logs

https://cran-archive.r-project.org/web/checks/2023/2023-02-02_check_results_animalTrack.html

### Additional information

* Archived on 2023-02-02 as issues were not corrected in time.
* [Announcement on the Tracking CTV repository](https://github.com/cran-task-views/Tracking/issues/54).
* [Issue opened on `animalTrack` repository](https://github.com/EdFarrell/animalTrack/issues/2).

Seems like simple edits could fix the issues:

* Remove the trailing period in the title (DESCRIPTION file);
* Replace the use of 'rgl::rgl.viewpoint()' by 'rgl::view3d()'.

**Comment by rociojoo** [comment]
removed
