### ISSUE TITLE
argosTrack: Fit Movement Models to Argos Data for Marine Animals

### ISSUE THREAD

**Issue by rociojoo** [cran-task-views/Tracking#60]
### Why was the package removed?

Does not pass CRAN check

### URL of the CRAN check logs

add after push

**Comment by rociojoo** [comment]
1 warning: 
`‘qpdf’ is needed for checks on size reduction of PDFs`

2 notes:
* One subdirectory of more than 1 mb
* `Found if() conditions comparing class() to string:
File ‘argosTrack/R/Animal.R’: if (class(observation) != "Observation") ...
File ‘argosTrack/R/Animal.R’: if (class(measurement) != "Measurement") ...
File ‘argosTrack/R/Measurement.R’: if (class(observation) != "Observation") ...
File ‘argosTrack/R/simTrack.R’: if (!class(observation) == "Observation") ...
Use inherits() (or maybe is()) instead.`

**Comment by basille** [comment]
Now passes CRAN checks.
