### ISSUE TITLE
Restore standard README

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/Tracking#63]
Mathieu @basille , I noticed that you modified the README file for the task view here on GitHub. Please restore the original README which is standardized across task views and should not be modified (see also the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md)). The additional information should go into the task view file itself which is the only document shown on CRAN which is the main access point for the task view.
Thanks in advance!

**Comment by basille** [comment]
Thanks @zeileis for pointing this out, I wasn't aware of the maintenance guidelines (I'll have a look ASAP). Going to restore README.md now — although I admit the standard version is rather terse and does not really invite to contribute.

**Comment by zeileis** [comment]
Thanks! We have written the maintenance guidelines earlier this year and I haven't advertised them a lot, yet.
And the README is intended to be minimal, mainly linking to the task view as the main source of information.

**Comment by basille** [comment]
Done.
